### ISSUE TITLE
Add release notes for 1.0 release

### ISSUE THREAD

**Issue by Susurrus** [rust-lang-nursery/bitflags#121]
I'm looking to upgrade to 1.0 to see how the documentation has improved, but there are no nice release notes for me to see what's changed or where that change came from as I'm running into issues with a macro now because of some change between 0.9 and 1.0. It'd help if there were release notes like there were for every other release.

**Comment by chetgurevitch** [comment]
Bump

**Comment by alexcrichton** [comment]
Unfortunately I'm pretty unlikely to get around to this, but if someone would like to contribute this that would be great!

**Comment by KodrAus** [comment]
@alexcrichton want to throw a `help-wanted` label on this one?

**Comment by alexcrichton** [comment]
Excellent idea!

**Comment by GabrielMajeri** [comment]
I've used Git to find a list of changes between `0.9.1` and `1.0.0`.

### Changes between 0.9.1 and 1.0.0

- **[breaking change**] Crate now generates associated constants (#24). Documentation has been updated to reflect this change.

- **[breaking change]** Minimum supported version is Rust 1.20, due to usage of associated constants.

- Support has been added for the `#[deprecated]` attribute (#112).

- Other improvements to unit tests and documentation (e.g. #106 and #115).

**Comment by alexcrichton** [comment]
Thanks! Want to send a PR creating a `CHANGELOG.md`?
